# Generated by Django 6.0.1 on 2026-03-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
