# Generated by Django 5.2.1 on 2026-04-13 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employer',
        ),
    ]
